
package de.xdevsoftware.jconwebapp.ui.column;

import com.flowingcode.vaadin.addons.ironicons.ImageIcons;
import com.rapidclipse.framework.server.data.renderer.RenderedComponent;
import com.rapidclipse.framework.server.ui.UIUtils;
import com.vaadin.flow.component.ClickEvent;
import com.vaadin.flow.component.ComponentEvent;
import com.vaadin.flow.component.ComponentEventListener;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;

import de.xdevsoftware.jconwebapp.model.Customer;
import de.xdevsoftware.jconwebapp.ui.desktop.CustomerView;
import de.xdevsoftware.jconwebapp.ui.dialog.CustomerEditDialog;


public class CustomerEditColumn extends VerticalLayout implements RenderedComponent<Customer>
{
	private Customer selectedCustomer;
	
	public CustomerEditColumn()
	{
		super();
		this.initUI();
	}

	@Override
	public void renderComponent(final Customer value)
	{
		this.selectedCustomer = value;
	}

	/**
	 * Event handler delegate method for the {@link Button} {@link #btnEdit}.
	 *
	 * @see ComponentEventListener#onComponentEvent(ComponentEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void btnEdit_onClick(final ClickEvent<Button> event)
	{
		new CustomerEditDialog(this.selectedCustomer)
			.onOkSubmit(() -> {
				final CustomerView customerView = UIUtils.getNextParent(this, CustomerView.class);
				customerView.loadData();
			})
			.open();
	}

	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.btnEdit = new Button();
		
		this.setPadding(false);
		this.btnEdit.addThemeVariants(ButtonVariant.LUMO_SMALL, ButtonVariant.LUMO_PRIMARY);
		this.btnEdit.setIcon(ImageIcons.EDIT.create());
		
		this.btnEdit.setSizeUndefined();
		this.add(this.btnEdit);
		this.setSizeUndefined();
		
		this.btnEdit.addClickListener(this::btnEdit_onClick);
	} // </generated-code>

	// <generated-code name="variables">
	private Button btnEdit;
	// </generated-code>
	
}
